structure(list(method = "GET", url = "https://thisdoesnotexist", 
    status_code = 404L, headers = structure(list(date = "Mon, 30 Jun 2025 09:43:40 GMT", 
        `content-type` = "application/json; charset=utf-8", `x-github-media-type` = "github.v3; format=json", 
        `x-github-api-version-selected` = "2022-11-28", `access-control-expose-headers` = "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset", 
        `access-control-allow-origin` = "*", `strict-transport-security` = "max-age=31536000; includeSubdomains; preload", 
        `x-frame-options` = "deny", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "0", `referrer-policy` = "origin-when-cross-origin, strict-origin-when-cross-origin", 
        `content-security-policy` = "default-src 'none'", vary = "Accept-Encoding, Accept, X-Requested-With", 
        `content-encoding` = "gzip", server = "github.com", `x-ratelimit-limit` = "60", 
        `x-ratelimit-remaining` = "26", `x-ratelimit-reset` = "1751277099", 
        `x-ratelimit-resource` = "core", `x-ratelimit-used` = "34", 
        `content-length` = "109", `x-github-request-id` = "EEB3:1A494:25DDA34:2723360:68625C4C"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\n  \"message\": \"Not Found\",\n  \"documentation_url\": \"https://docs.github.com/rest\",\n  \"status\": \"404\"\n}\n"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
