
#' Check whether all man files have been generated by 'roxygen2'
#'
#' @param path Path to local source repository
#' @return 'TRUE' if all files generated by 'roxygen2', otherwise 'FALSE'
#' @noRd
pkg_uses_roxygen2 <- function (path) {

    rd <- list.files (file.path (path, "man"),
                      pattern = "\\.Rd$",
                      full.names = TRUE)

    chk <- vapply (rd, function (i) {
                       l1 <- readLines (i, n = 1L, encoding = "UTF-8")
                       grepl ("Generated by roxygen2", l1, ignore.case = TRUE)
                       },
                       logical (1),
                       USE.NAMES = FALSE)

    return (all (chk))
}

#' Check whether package has 'contributing.md', as well as whether it has a
#' life cycle statement
#'
#' @inheritParams pkg_uses_roxygen2
#' @return Vector of two logical values, the first one identifying whether a
#' package has a 'contributing.md' file or not; the second whether this file has
#' a life cycle statement
#' @noRd
pkg_has_contrib_md <- function (path) {

    flist <- list.files (path,
                         all.files = TRUE,
                         recursive = TRUE,
                         full.names = TRUE)

    # contributing either with or without ".md" extension:
    ptn <- paste0 (.Platform$file.sep, "contributing", c ("$", "\\.md$"))
    f <- grep (paste0 (ptn, collapse = "|"), flist, ignore.case = TRUE)

    has_lifecycle <- FALSE
    if (length (f) == 1L) {

        contrib <- readLines (flist [f], encoding = "UTF-8")

        has_lifecycle <- any (grepl ("life\\s?cycle",
                                     contrib,
                                     ignore.case = TRUE))
    }

    return (c (has_contrib = length (f) == 1L,
               has_lifecycle = has_lifecycle))
}

#' Check whether a package has a `inst/CITATION` file
#'
#' This does no check the contents of that file in any way.
#' @noRd
pkg_has_citation <- function (path) {

    "CITATION" %in% list.files (file.path (path, "inst"))
}

#' Check whether a package has a `codemeta.json` file
#'
#' @noRd
pkg_has_codemeta <- function (path) {

    "codemeta.json" %in% list.files (path, recursive = FALSE)
}


get_Rd_meta <- utils::getFromNamespace (".Rd_get_metadata", "tools") # nolint


pkg_on_cran <- function (path) {

    desc <- data.frame (read.dcf (file.path (path, "DESCRIPTION")))
    pkg <- desc$Package

    ap <- data.frame (utils::available.packages ())
    res <- pkg %in% ap$Package

    if (res) {
        # Check whether CRAN package of that name has same title

        u <- paste0 ("https://cran.r-project.org/web/packages/",
                     pkg, "/index.html")
        x <- rvest::read_html (u)
        h2 <- paste0 (rvest::html_elements (x, "h2"))
        h2 <- gsub ("<h2>|<\\/h2>", "", h2)
        res <- grepl (desc$Title, h2, ignore.case = TRUE)
    }

    return (res)
}
