
#' Check whether all man files have been generated by 'roxygen2'
#'
#' @param path Path to local source repository
#' @return 'TRUE' if all files generated by 'roxygen2', otherwise 'FALSE'
#' @noRd
pkgchk_uses_roxygen2 <- function (path) {

    rd <- list.files (file.path (path, "man"),
                      pattern = "\\.Rd$",
                      full.names = TRUE)

    chk <- vapply (rd, function (i) {
                       l1 <- readLines (i, n = 1L, encoding = "UTF-8")
                       grepl ("Generated by roxygen2", l1, ignore.case = TRUE)
                       },
                       logical (1),
                       USE.NAMES = FALSE)

    return (all (chk))
}

output_pkgchk_uses_roxygen2 <- function (checks) {

    out <- list (check_pass = checks$checks$uses_roxy,
                summary = "",
                print = "") # no print method

    out$summary <- ifelse (out$check_pass,
                           "uses 'roxygen2'.",
                           "does not use 'roxygen2'.")

    return (out)
}
