
#' Check whether all man files have been generated by 'roxygen2'
#'
#' @param path Path to local source repository
#' @return 'TRUE' if all files generated by 'roxygen2', otherwise 'FALSE'
#' @export
pkg_uses_roxygen2 <- function (path) {

    rd <- list.files (file.path (path, "man"),
                      pattern = "\\.Rd$",
                      full.names = TRUE)

    chk <- vapply (rd, function (i) {
                       l1 <- readLines (i, n = 1L, encoding = "UTF-8")
                       grepl ("Generated by roxygen2", l1, ignore.case = TRUE)
                       },
                       logical (1),
                       USE.NAMES = FALSE)

    return (all (chk))
}

#' Check whether package has 'contributing.md', as well as whether it has a
#' life cycle statement
#'
#' @inheritParams pkg_uses_roxygen2
#' @return Vector of two logical values, the first one identifying whether a
#' package has a 'contributing.md' file or not; the second whether this file has
#' a life cycle statement
#' @export
pkg_has_contrib_md <- function (path) {

    flist <- list.files (path, full.names = TRUE)

    f <- grep (paste0 (.Platform$file.sep, "contributing\\.md$"),
               flist,
               ignore.case = TRUE)

    has_lifecycle <- FALSE
    if (length (f) == 1L) {

        contrib <- readLines (flist [f], encoding = "UTF-8")

        has_lifecycle <- any (grepl ("life\\s?cycle",
                                     contrib,
                                     ignore.case = TRUE))
    }

    return (c (has_contrib = length (f) == 1L,
               has_lifecycle = has_lifecycle))
}


get_Rd_meta <- utils::getFromNamespace (".Rd_get_metadata", "tools") # nolint


#' Check whether all functions have examples
#'
#' @inheritParams pkg_uses_roxygen2
#' @return Vector of named logical values, one for each '.Rd' file indicating
#' whether or not it has example lines.
#' @export
all_pkg_fns_have_exs <- function (path) {

    rd <- list.files (file.path (path, "man"),
                      pattern = "\\.Rd$",
                      full.names = TRUE)

    has_ex <- vapply (rd, function (i) {
                          rd_i <- tools::parse_Rd (i)
                          ex <- get_Rd_meta (rd_i, "examples")
                          length (ex) > 0
                      },
                      logical (1),
                      USE.NAMES = TRUE)

    names (has_ex) <-
        vapply (names (has_ex), function (i)
                utils::tail (strsplit (i, .Platform$file.sep) [[1]], 1),
                character (1))

    return (has_ex)
}


#' CI results for GitHub only
#' @inheritParams pkg_uses_roxygen2
#' @return A 'data.frame' with one row for each GitHub workflow, and columns for
#' name, the 'conclusion' status, the git 'sha', and the date.
#' @export
ci_results <- function (path) {

    d <- data.frame (read.dcf (file.path (path, "DESCRIPTION")))
    if (!"URL" %in% names (d))
        return ("Error: Description has no URL")

    url <- strsplit (d$URL, "\\/") [[1]]
    org <- utils::tail (url, 2) [1]
    repo <- utils::tail (url, 1)

    url <- paste0 ("https://api.github.com/repos/",
                   org,
                   "/",
                   repo,
                   "/actions/runs")

    runs <- httr::GET (url) %>% httr::content ()

    if (runs$total_count == 0)
        return (NULL)

    dat <- lapply (runs$workflow_runs, function (i)
                   data.frame (name = i$name,
                               status = i$status,
                               conclusion = i$conclusion,
                               sha = i$head_sha,
                               time = i$created_at))
    dat <- do.call (rbind, dat)
    dat$time <- strptime (dat$time, "%Y-%m-%dT%H:%M:%SZ")
    dat$time_dbl <- as.double (dat$time)
    # non-dply group_by %>% summarise:
    dat <- lapply (split (dat, f = as.factor (dat$name)),
                   function (i)
                       i [which.max (i$time_dbl), ])
    dat <- do.call (rbind, dat)

    dat$sha <- substring (dat$sha, 1, 6)
    dat$date <- strftime (dat$time, "%Y-%m-%d")
    rownames (dat) <- dat$time_dbl <- dat$time <- dat$status <- NULL

    return (dat)
}

#' Check that left-assignment operators are used consistently throughout a
#' package. "LEFT_ASSIGN" tokens can also be `:=`, so these must also be
#' tallied, but are ignored.
#' Left-assign operators are: ["=", "<-", "<<-", ":="].
#' https://github.com/wch/r-source/blob/trunk/src/main/gram.y#L3283-L3290
#' https://github.com/wch/r-source/blob/trunk/src/main/gram.y#L3346-L3349
#' @inheritParams pkg_uses_roxygen2
#' @return Named vector of 2 values tallying instances of usage of `<-` and `=`.
#' @export
left_assign <- function (path) {

    rdir <- file.path (path, "R")
    if (!file.exists (rdir))
        return (c ("<-" = 0L,
                   "=" = 0L))

    rdir <- normalizePath (rdir)
    flist <- list.files (rdir,
                         full.names = TRUE,
                         pattern = "\\.q$|\\.r$|\\.s$",
                         ignore.case = TRUE)

    assigns <- vapply (flist, function (i) {
                           p <- tryCatch (utils::getParseData (parse (i)),
                                          error = function (e) NULL)
                           if (is.null (p))
                               return (NULL)
                           assigns <- table (p$text [which (p$token ==
                                                            "LEFT_ASSIGN")])
                           # sort order: ":=", "<-", "<<-", "="
                           if (!":=" %in% names (assigns))
                               assigns <- c (":=" = 0L, assigns)
                           if (!"<-" %in% names (assigns))
                               assigns <- c ("<-" = 0L, assigns)
                           if (!"<<-" %in% names (assigns))
                               assigns <- c ("<<-" = 0L, assigns)
                           if (!"=" %in% names (assigns))
                               assigns <- c (assigns, "=" = 0L)

                           return (assigns)
                         },
                         integer (4),
                         USE.NAMES = TRUE)
    assigns <- rowSums (assigns)
    # rm `:=`:
    assigns <- assigns [which (!names (assigns) == ":=")]

    return (assigns)
}
