
#' Check whether all man files have been generated by 'roxygen2'
#'
#' @param path Path to local source repository
#' @return 'TRUE' if all files generated by 'roxygen2', otherwise 'FALSE'
#' @export
pkg_uses_roxygen2 <- function (path) {

    man <- list.files (file.path (path, "man"),
                       pattern = "\\.Rd$",
                       full.names = TRUE)

    chk <- vapply (man, function (i) {
                       l1 <- readLines (i, n = 1L, encoding = "UTF-8")
                       grepl ("Generated by roxygen2", l1, ignore.case = TRUE)
                       },
                       logical (1),
                       USE.NAMES = FALSE)

    return (all (chk))
}

#' Check whether package has 'contributing.md', as well as whether it has a
#' life cycle statement
#'
#' @inheritParams pkg_uses_roxygen2
#' @export
pkg_has_contrib_md <- function (path, check_lifecycle = TRUE) {

    flist <- list.files (path, full.names = TRUE)

    f <- grep (paste0 (.Platform$file.sep, "contributing\\.md$"),
               flist,
               ignore.case = TRUE)

    has_lifecycle <- FALSE
    if (length (f) == 1L) {

        contrib <- readLines (flist [f], encoding = "UTF-8") 

        has_lifecycle <- any (grepl ("life\\s?cycle", contrib, ignore.case = TRUE))
    }

    return (c (has_contrib = length (f) == 1L,
               has_lifecycle = has_lifecycle))
}
