name: Renew token issue
on:
  schedule:
    - cron: 0 0 1 */2 *

jobs:
  
  issue_comment:

    name: Renew token issue

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:

      - name: Create Issue Comment
        uses: actions/github-script@v8
        with:
          script: |

            github.rest.issues.createComment({
              owner: "ropensci-review-tools",
              repo: "pkgcheck",
              issue_number: 123,
              body: 
                `@mpadge It's time to renew your 'RRT_TOKEN'

                 - (Re-)Generate **personal** token called 'RRT_TOKEN', with 90 day expiry
                 - grant both repo and workflow access
                 - copy token to \'pkgcheck\' and \'pkgcheck-action\' repo secrets`
            })
